IEvangelist/azure-cosmos-dotnet-repository

Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs
Ensures the item returned is of the same type as requested.
=> Added type check to Get(string id).

Microsoft.Azure.CosmosRepository.Samples/ServiceTier/Program.cs, Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs, Microsoft.Azure.CosmosRepository/src/IRepository.cs
Added a function overload for GetByQueryAsync allowing users to put their query parameters
=> Add Cosmos GetByQueryAsync function overload with QueryDefinition

Microsoft.Azure.CosmosRepository/src/Attributes/UniqueKeyAttribute.cs, Microsoft.Azure.CosmosRepository/src/Extensions/ServiceCollectionExtensions.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosUniqueKeyPolicyProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/ICosmosUniqueKeyPolicyProvider.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosUniqueKeyPolicyProvider.cs
- Addes the UniqueKeyAttribute
- Addes IUniqueKeyPolicyProvider and a default implementation
- Addes Tests for the Provider
- Uses the policies when creating a container 
Fixes #46
=> Implements Unique-Key possibility (issue #46)

README.md
=> Updated readme to include discord channel

Microsoft.Azure.CosmosRepository.Samples/AzureFunctionTier/AzureFunctionTier.csproj, Microsoft.Azure.CosmosRepository.Samples/AzureFunctionTier/Model/User.cs, Microsoft.Azure.CosmosRepository.Samples/AzureFunctionTier/Startup.cs, Microsoft.Azure.CosmosRepository.Samples/AzureFunctionTier/local.settings.json.example, Microsoft.Azure.CosmosRepository.Samples/ServiceTier/Program.cs, Microsoft.Azure.CosmosRepository/src/Builders/DefaultItemContainerBuilder.cs, Microsoft.Azure.CosmosRepository/src/Builders/IItemContainerBuilder.cs, Microsoft.Azure.CosmosRepository/src/Extensions/ServiceCollectionExtensions.cs, Microsoft.Azure.CosmosRepository/src/Options/ContainerOptions.cs, Microsoft.Azure.CosmosRepository/src/Options/RepositoryOptions.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerNameProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosPartitionKeyPathProvider.cs, Microsoft.Azure.CosmosRepository/test/Microsoft.Azure.CosmosRepositoryTests.csproj, Microsoft.Azure.CosmosRepository/test/Options/RepositoryOptionsTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosClientProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerNameProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosPartitionKeyPathProviderTests.cs
Closes #71
This is still very much open for discussion would love some opinions on this I really like alternative of using attributes on the objects.
=> Alternate Configuration for Items Container & Partition Key

.github/workflows/nuget-publish.yml
=> Publish Updates

Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs, Microsoft.Azure.CosmosRepository/src/Extensions/ServiceCollectionExtensions.cs, Microsoft.Azure.CosmosRepository/src/Processors/DefaultCosmosQueryableProcessor.cs, Microsoft.Azure.CosmosRepository/src/Processors/ICosmosQueryableProcessor.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultRepositoryExpressionProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/IRepositoryExpressionProvider.cs, Microsoft.Azure.CosmosRepository/test/DefaultRepositoryTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Stubs/TestItem.cs
Some work to get some UT coverage over the `DefaultRepository`
=> Default Repository Unit Tests

.github/workflows/pre-release-nuget.yml
This should mean that tags made on the branch `dev/v3` and take the form of `3.Minor.Patch-pre{build-number}` will trigger a pipeline to run and create a pre-release Nuget package.
Closes #103
=> Pre release package yml

Microsoft.Azure.CosmosRepository/src/Builders/ContainerOptionsBuilder.cs, Microsoft.Azure.CosmosRepository/src/Extensions/ServiceCollectionExtensions.cs, Microsoft.Azure.CosmosRepository/src/Options/ItemOptions.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerDefaultTimeToLiveProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerNameProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosItemConfigurationProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/ICosmosContainerDefaultTimeToLiveProvider.cs, Microsoft.Azure.CosmosRepository/test/Abstractions/WithRepositoryOptions.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerDefaultTimeToLiveProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosItemConfigurationProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Stubs/AnotherTestItem.cs
=> Added default time to live to a container configuration

Microsoft.Azure.CosmosRepository.Samples/AzureFunctionTier/AzureFunctionTierPostmanCollection.json, Microsoft.Azure.CosmosRepository.Samples/AzureFunctionTier/Startup.cs, Microsoft.Azure.CosmosRepository/src/Builders/ContainerOptionsBuilder.cs, Microsoft.Azure.CosmosRepository/src/Extensions/ServiceCollectionExtensions.cs, Microsoft.Azure.CosmosRepository/src/Options/ItemOptions.cs, Microsoft.Azure.CosmosRepository/src/Options/RepositoryOptions.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultContainerSyncContainerPropertiesProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerDefaultTimeToLiveProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerNameProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosItemConfigurationProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosPartitionKeyPathProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/ICosmosContainerDefaultTimeToLiveProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/ICosmosContainerProvider.cs, Microsoft.Azure.CosmosRepository/src/Providers/ICosmosContainerSyncContainerPropertiesProvider.cs, Microsoft.Azure.CosmosRepository/src/Services/DefaultCosmosContainerService.cs, Microsoft.Azure.CosmosRepository/src/Services/DefaultCosmosContainerSyncService.cs, Microsoft.Azure.CosmosRepository/src/Services/ICosmosContainerService.cs, Microsoft.Azure.CosmosRepository/src/Services/ICosmosContainerSyncService.cs, Microsoft.Azure.CosmosRepository/test/Abstractions/WithRepositoryOptions.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultContainerSyncContainerPropertiesProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerDefaultTimeToLiveProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosContainerProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosItemConfigurationProviderTests.cs, Microsoft.Azure.CosmosRepository/test/Services/DefaultCosmosContainerServiceTests.cs, Microsoft.Azure.CosmosRepository/test/Services/DefaultCosmosContainerSyncServiceTests.cs, Microsoft.Azure.CosmosRepository/test/Stubs/AnotherTestItem.cs, Microsoft.Azure.CosmosRepository/test/Stubs/TestCosmosClientProvider.cs
=> Container syncing

Microsoft.Azure.CosmosRepository/src/Options/RepositoryOptions.cs, Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosClientProvider.cs
=> Added support to provide a managed identity option

Microsoft.Azure.CosmosRepository/src/Services/DefaultCosmosContainerService.cs, Microsoft.Azure.CosmosRepository/test/Services/DefaultCosmosContainerServiceTests.cs
=> Only sync a shared container once

Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs, Microsoft.Azure.CosmosRepository/src/IRepository.cs, Microsoft.Azure.CosmosRepository/src/InMemoryRepository.cs, Microsoft.Azure.CosmosRepository/test/InMemoryRepositoryTests.cs
Added logic to enable bulk update to cosmos repo
Closes #127
=> Bulk update #127

Microsoft.Azure.CosmosRepository.Samples/WebTier/Controllers/LanguageController.cs, Microsoft.Azure.CosmosRepository.Samples/WebTier/WebTier.csproj, Microsoft.Azure.CosmosRepository.Samples/WebTier/appsettings.Development.json, Microsoft.Azure.CosmosRepository/src/Builders/IPatchOperationBuilder.cs, Microsoft.Azure.CosmosRepository/src/Builders/PatchOperationBuilder.cs, Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs, Microsoft.Azure.CosmosRepository/src/Extensions/ExpressionExtensions.cs, Microsoft.Azure.CosmosRepository/src/IRepository.cs, Microsoft.Azure.CosmosRepository/src/InMemoryRepository.cs, Microsoft.Azure.CosmosRepository/src/Internals/InternalPatchOperation.cs, Microsoft.Azure.CosmosRepository/src/Microsoft.Azure.CosmosRepository.csproj, Microsoft.Azure.CosmosRepository/test/Builders/PatchOperationBuilderTests.cs, Microsoft.Azure.CosmosRepository/test/InMemoryRepositoryTests.cs, Microsoft.Azure.CosmosRepository/test/Services/DefaultCosmosContainerServiceTests.cs
=> Support Partial Replace Updates

src/Microsoft.Azure.CosmosRepository.AspNetCore/CosmosRepositoryChangeFeedHostedService.cs, src/Microsoft.Azure.CosmosRepository.AspNetCore/Extensions/ServiceCollectionExtensions.cs
Few issues I spotted when testing this out for myself.
=> Fixed DI registration

src/Microsoft.Azure.CosmosRepository/DefaultRepository.cs, src/Microsoft.Azure.CosmosRepository/Logging/EventIds.cs, src/Microsoft.Azure.CosmosRepository/Logging/LoggerExtensions.cs, src/Microsoft.Azure.CosmosRepository/Logging/LoggerMessageDefinitions.cs, src/Microsoft.Azure.CosmosRepository/Microsoft.Azure.CosmosRepository.csproj, src/Microsoft.Azure.CosmosRepository/Processors/DefaultCosmosQueryableProcessor.cs, src/Microsoft.Azure.CosmosRepository/Processors/ICosmosQueryableProcessor.cs, tests/Microsoft.Azure.CosmosRepositoryTests/DefaultRepositoryTests.cs
Added some basic logging following the [high-performance logging guidance](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-6.0).
Closes #174 
I still think we can do a little more of this for some of the create & update operations.
I plan to add a docs page for this @IEvangelist if you approve of this 😊
=> Added some basic logging for read operations

Microsoft.Azure.CosmosRepository.sln, src/Microsoft.Azure.CosmosRepository/Builders/ContainerOptionsBuilder.cs, src/Microsoft.Azure.CosmosRepository/Providers/DefaultCosmosThroughputProvider.cs, tests/Microsoft.Azure.CosmosRepositoryTests/Providers/DefaultCosmosThroughputProviderTests.cs
Hey @mumby0168 - this is what we were talking about. I think it's what we'd need, have a look.
=> VS'22 and added support for serverless resources, null throughput

.github/workflows/build-validation.yml, docs/index.md, docs/unique-key-policy.md, src/Microsoft.Azure.CosmosRepository/Attributes/UniqueKeyAttribute.cs, src/Microsoft.Azure.CosmosRepository/Microsoft.Azure.CosmosRepository.csproj, src/Microsoft.Azure.CosmosRepository/Providers/DefaultCosmosUniqueKeyPolicyProvider.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/ChangeFeedBasicTests.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/CosmosRepositoryAcceptanceTest.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/Models/Rating.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/Models/UniqueKeyPolicyItem.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/RepositoryBasicsTests.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/UniqueKeyPolicyTests.cs, tests/Microsoft.Azure.CosmosRepositoryTests/Providers/DefaultCosmosUniqueKeyPolicyProviderTests.cs
=> Unique Key Policy Improvements

.gitignore, docs/content/4-change-feed/_index.md, src/Microsoft.Azure.CosmosRepository/ChangeFeed/ChangeFeedOptions.cs, src/Microsoft.Azure.CosmosRepository/ChangeFeed/DefaultConatinerChangeFeedProcessor.cs, src/Microsoft.Azure.CosmosRepository/ChangeFeed/IItemChangeFeedProcessor.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/CosmosRepositoryAcceptanceTest.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/DisabledStrictTypeCheckingTests.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/EnabledStrictTypeCheckingTests.cs, tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/UniqueKeyPolicyTests.cs, tests/Microsoft.Azure.CosmosRepositoryTests/ChangeFeed/Processors/DefaultChangeFeedContainerProcessorTests.cs
- update gitignore
- Started on docs for change feed
=> Change Feed Docs

samples/EventSourcingJobsTracker/Application/Services/DefaultJobsTrackerService.cs, samples/EventSourcingJobsTracker/Application/Services/IJobsTrackerService.cs, samples/EventSourcingJobsTracker/Endpoints/JobEndpoints.cs, samples/EventSourcingJobsTracker/Endpoints/JobsListsEndpoints.cs, src/Microsoft.Azure.CosmosEventSourcing/Events/AtomicEvent.cs
I stick to my word @IEvangelist  ;)
=> Add async suffixes

.github/workflows/es_docs_deploy.yaml
@IEvangelist I need to add an access token to my new repo for the docs site
=> ES docs deploy

.github/workflows/es_docs_deploy.yaml
Stole this one from here.
I am hoping this works ......
https://github.com/MassTransit/MassTransit/blob/develop/.github/workflows/docs.yml
=> Try again with docs deploy

Microsoft.Azure.CosmosRepository.sln, docs/event-sourcing/src/.vuepress/config.js, docs/event-sourcing/src/event-store/README.md, docs/event-sourcing/src/features/README.md, docs/event-sourcing/src/getting-started/README.md, docs/event-sourcing/src/getting-started/motivation.md, docs/event-sourcing/src/projections/README.md, samples/EventSourcingCustomerAccount/Aggregates/CustomerAccount.cs, samples/EventSourcingCustomerAccount/EventSourcingCustomerAccount.csproj, samples/EventSourcingCustomerAccount/Events/CustomerAccountAddressAssigned.cs, samples/EventSourcingCustomerAccount/Events/CustomerAccountCreated.cs, samples/EventSourcingCustomerAccount/Items/CustomerAccountEventItem.cs, samples/EventSourcingCustomerAccount/Models/CustomerAddress.cs, samples/EventSourcingCustomerAccount/Program.cs, samples/EventSourcingCustomerAccount/Requests/AssignCustomersAccountAddressRequest.cs, samples/EventSourcingCustomerAccount/Requests/CreateCustomerAccountRequest.cs, samples/EventSourcingCustomerAccount/appsettings.Development.json, samples/EventSourcingCustomerAccount/appsettings.json
Added some getting started docs and another small sample app as a starting point.
This hasn't covered projections yet, felt this is worthy of another section.
=> Getting started docs

src/Microsoft.Azure.CosmosEventSourcing/Aggregates/IAggregateRootMapper.cs, src/Microsoft.Azure.CosmosEventSourcing/Exceptions/AtomocEventEtagRequiredException.cs, src/Microsoft.Azure.CosmosEventSourcing/Exceptions/ReplayMethodNotDefinedException.cs, src/Microsoft.Azure.CosmosEventSourcing/Extensions/ServiceCollectionExtensions.cs, src/Microsoft.Azure.CosmosEventSourcing/Items/DefaultEventItem.cs, src/Microsoft.Azure.CosmosEventSourcing/Stores/DefaultEventStore.Def.cs, src/Microsoft.Azure.CosmosEventSourcing/Stores/DefaultEventStore.Read.cs, src/Microsoft.Azure.CosmosEventSourcing/Stores/DefaultEventStore.Write.cs, src/Microsoft.Azure.CosmosEventSourcing/Stores/IEventStore.cs, src/Microsoft.Azure.CosmosEventSourcing/Stores/IReadOnlyEventStore.cs, src/Microsoft.Azure.CosmosEventSourcing/Stores/IWriteOnlyEventStore.cs, tests/Microsoft.Azure.CosmosEventSourcingTests/Extensions/ObjectExtensions.cs, tests/Microsoft.Azure.CosmosEventSourcingTests/Stores/EventStoreTests.ReadAggregate.cs, tests/Microsoft.Azure.CosmosEventSourcingTests/Testing.cs
Used partials, introduced read vs write interfaces, added a method that looks for a static Replay method.
Added the concept of mappers to map to and from `AggregateRoot`'s
=> Refactored DefaultEventStore into partials & and added ReadAggregateAsync method

samples/Microsoft.Azure.CosmosEventSourcing/BasicEventSourcingSample/BasicEventSourcingSample.csproj, samples/Microsoft.Azure.CosmosEventSourcing/BasicEventSourcingSample/Program.cs, src/Microsoft.Azure.CosmosEventSourcing/Aggregates/IAggregateRoot.cs, src/Microsoft.Azure.CosmosRepository/Extensions/ConfigurationExtensions.cs, src/Microsoft.Azure.CosmosRepository/Options/RepositoryOptions.cs
Config extensions useful when manipulating config in functional tests and when using health check packages.
=> Interface tweak & config extensions

src/Microsoft.Azure.CosmosEventSourcing/Aggregates/AggregateRoot.cs, src/Microsoft.Azure.CosmosEventSourcing/Events/AtomicEvent.cs, src/Microsoft.Azure.CosmosEventSourcing/Events/DomainEvent.cs, src/Microsoft.Azure.CosmosEventSourcing/Events/IDomainEvent.cs, src/Microsoft.Azure.CosmosEventSourcing/Items/EventItem.cs, tests/Microsoft.Azure.CosmosEventSourcingAcceptanceTests/AcceptanceTests.Execute.cs, tests/Microsoft.Azure.CosmosEventSourcingAcceptanceTests/Projections/TodoItemProjections.cs, tests/Microsoft.Azure.CosmosEventSourcingTests/Aggregates/AggregateRootTests.cs, tests/Microsoft.Azure.CosmosEventSourcingTests/Items/EventItemTests.cs, tests/Microsoft.Azure.CosmosEventSourcingTests/Stores/EventStoreTests.ReadAggregate.cs, tests/Microsoft.Azure.CosmosEventSourcingTests/Stores/EventStoreTests.cs
Added a unique GUID to identify every event. The plan is to use this later to implement an inbox to help not process the same event more than once.
=> Unique Event IDs

src/Microsoft.Azure.CosmosEventSourcing/Builders/DefaultCosmosEventSourcingBuilder.cs, src/Microsoft.Azure.CosmosEventSourcing/Builders/ICosmosEventSourcingBuilder.cs, src/Microsoft.Azure.CosmosEventSourcing/ChangeFeed/DefaultEventSourcingProcessor.cs, src/Microsoft.Azure.CosmosEventSourcing/Options/EventSourcingProcessorOptions.cs
Fix bit missed off as part of PR #262
=> Make processor options be registered with the `IProjectionKey`

src/Microsoft.Azure.CosmosRepository/Extensions/ValueTaskExtensions.cs
Adding additional extension methods to the to the ValueTaskExtensions.
The existing ToListAsync() Method did not have any tests, I did not add any for the other methods. If needed I can add additional tests.
Resolves: #280
=> FirstAsync(), FirstOrDefaultAsync(), LastAsync(), and LastOrDefault.

tests/Microsoft.Azure.CosmosEventSourcingAcceptanceTests/AcceptanceTests.Setup.cs
Kicked off the following build which will run the tests, should allow us to see the polly policy take effect:
https://github.com/IEvangelist/azure-cosmos-dotnet-repository/actions/runs/3832581468
=> Add polly policy to wrap change feed start in event sourcing acceptance tests

src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Count.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Create.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Delete.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Exists.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Paging.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Read.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Specs.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Update.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.cs, src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryStorage.cs, tests/Microsoft.Azure.CosmosRepositoryTests/InMemoryRepositoryTests.cs
=> fix: consistent data across in-memory repository between interfaces
