IEvangelist/azure-cosmos-dotnet-repository

Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs
Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerProvider.cs

Consistent usage of `ConfigureAwait(false)`
You could also enable FxCop with
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007?view=vs-2019
enabled. Happy to send another PR

ConfigureAwait

---

Microsoft.Azure.CosmosRepository/src/Microsoft.Azure.CosmosRepository.csproj

This issue resolves an issue where a version of `Microsoft.Extensions.Options.ConfigurationExtensions` was incompatible with the v3 Azure Functions host. The fix is to change the version from `5.0.0` to `3.1.10`.
Fixes #23

Revert ConfigurationExtensions version

---

Microsoft.Azure.CosmosRepository/src/Attributes/PartitionKeyPathAttribute.cs
Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs
Microsoft.Azure.CosmosRepository/src/DefaultRepositoryFactory.cs
Microsoft.Azure.CosmosRepository/src/IItem.cs
Microsoft.Azure.CosmosRepository/src/IRepository.cs
Microsoft.Azure.CosmosRepository/src/IRepositoryFactory.cs
Microsoft.Azure.CosmosRepository/src/Item.cs
Microsoft.Azure.CosmosRepository/src/Microsoft.Azure.CosmosRepository.csproj
Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerProvider.cs
Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosPartitionKeyPathProvider.cs
Microsoft.Azure.CosmosRepository/src/Providers/ICosmosContainerProvider.cs
Microsoft.Azure.CosmosRepository/src/Providers/ICosmosPartitionKeyPathProvider.cs
Microsoft.Azure.CosmosRepository/test/DefaultRepositoryFactoryTests.cs
Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosPartitionKeyPathProviderTests.cs

Per [this discussion](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/issues/35), this PR creates an `IItem` abstraction over the Item class, to allow for a custom implementation of the concrete base class when desired. A typical use case is in a brownfield scenario with an existing base entity class, and/or scenarios where base adaptors for multiple databases need to coexist in the same entity. An example usage is shown in _DefaultRepositoryFactoryTests.cs_ [here](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/compare/main...dcuccia:main#diff-ecc142928f54ba144c938a65907992fb12fc8b7d7560fe2d147377728d7fb462). This is primarily to show the usage of the interface - clearly, we might do more to test this, beyond the 1-liner addition to …

IItem abstraction to allow for custom base item classes

---

Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs
Microsoft.Azure.CosmosRepository/src/IItem.cs
Microsoft.Azure.CosmosRepository/src/Item.cs
Microsoft.Azure.CosmosRepository/test/DefaultRepositoryFactoryTests.cs
Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosPartitionKeyPathProviderTests.cs

@IEvangelist I got around to using the `IItem` interface we created in [PR 36](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/pull/36), and realized there was still a hard dependency on the `PartitionKey` type. This was quite inconvenient, because I had to pull in Cosmos at my contracts/DTO layer. This PR would change that type to a string, and push the `PartitionKey` ctor call to the repository level, at the time of calling `CreateItemAsync`/`UpsertItemAsync`. There was not caching of this value anyway, so I don't think there would be a performance difference in any case. Does this look ok? Anything different/else you'd want to do here?
Thanks!
David

Relax IItem PartitionKey type to string to remove Cosmos dependency

---

.github/workflows/nuget-publish.yml

This will start the build when a tag is added to master branch such as `v1.1` this then extracts the version number from it and versions the package with this version which is then published to nuget.org.

Auto deploy to nuget on a tag

---

Microsoft.Azure.CosmosRepository.Samples/AzureFunctionTier/Startup.cs
Microsoft.Azure.CosmosRepository/src/Builders/ContainerOptionsBuilder.cs
Microsoft.Azure.CosmosRepository/src/Extensions/ServiceCollectionExtensions.cs
Microsoft.Azure.CosmosRepository/src/Options/ItemOptions.cs
Microsoft.Azure.CosmosRepository/src/Options/RepositoryOptions.cs
Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosContainerDefaultTimeToLiveProvider.cs
Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosItemConfigurationProvider.cs
Microsoft.Azure.CosmosRepository/src/Providers/DefaultCosmosThroughputProvider.cs
Microsoft.Azure.CosmosRepository/src/Providers/ICosmosThroughputProvider.cs
Microsoft.Azure.CosmosRepository/src/Services/DefaultCosmosContainerService.cs
Microsoft.Azure.CosmosRepository/test/Options/RepositoryOptionsTests.cs
Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosItemConfigurationProviderTests.cs
Microsoft.Azure.CosmosRepository/test/Providers/DefaultCosmosThroughputProviderTests.cs
Microsoft.Azure.CosmosRepository/test/Services/DefaultCosmosContainerServiceTests.cs

Closes #107.
There are, however, a few nuances around this that are going to need to be documented see below:
1. A container cannot switch between manual & autoscale throughput.
2. If a container has already been created with no throughput properties then these cannot be applied.
See some documentation here: https://docs.microsoft.com/en-us/azure/cosmos-db/set-throughput#update-throughput-on-a-database-or-a-container

Specify RU/s at the container level

---

Microsoft.Azure.CosmosRepository/src/Builders/PatchOperationBuilder.cs
Microsoft.Azure.CosmosRepository/test/Builders/PatchOperationBuilderTests.cs

Updated the attribute checking as when I was testing with my POCO it had additional attributes, in my example [Required] for validation, and it was failing on the update.

Fix error being thrown when additional attributes are applied to poco classes

---

docs/partitioning-setup.md

Basic explanation of how you can configure a partitioning strategy using the library. This was driven from the issue raised here #175.
There are still a few things I would like to add:
* Advice section, we set all partition keys on _all_ containers to `/partitionKey` this gives flexibility to change the PK if we decide it wasn't the best. It also allows _all_ items to be shared in a single container.
* Some some sort of FAQs or common errors and how to fix them, just some bits from personal experience.

Start on the partitioning strategy docs

---

.github/workflows/build-validation.yml
Microsoft.Azure.CosmosRepository.sln
tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/CosmosRepositoryAcceptanceTest.cs
tools/CosmosTestHelper/CosmosTestHelper.csproj
tools/CosmosTestHelper/Program.cs

* The tests now run on a database that includes their OS name to avoid clashes.
* Turned on batch builds, only run one master CI build at a time, newest wins.
* Added a small console app to clear down the databases at the beginning of a test run.

Test CI Improvements

---

src/Microsoft.Azure.CosmosRepository/EtagItem.cs
src/Microsoft.Azure.CosmosRepository/FullItem.cs
src/Microsoft.Azure.CosmosRepository/InMemoryRepository.cs
tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/RepositoryBasicsTests.cs
tests/Microsoft.Azure.CosmosRepositoryTests/InMemoryRepositoryTests.cs

Updated the in memory repository to reflect the real behaviour when upserting items.
Added the ability to set the etag in the constructor this will allow the items to be mapped to and from other objects without losing this data.
- Changed item with etag to be abstract

Updated etag in memory repository behaviour 

---

samples/Paging/Program.cs
samples/Specification/FullSpecificationSamples.cs
samples/Specification/SpecificationPagingSamples.cs
src/Microsoft.Azure.CosmosRepository/DefaultRepository.cs
src/Microsoft.Azure.CosmosRepository/IRepository.cs
src/Microsoft.Azure.CosmosRepository/InMemoryRepository.cs
src/Microsoft.Azure.CosmosRepository/Paging/IPage.cs
src/Microsoft.Azure.CosmosRepository/Paging/IPageQueryResult.cs
src/Microsoft.Azure.CosmosRepository/Paging/Page.cs
src/Microsoft.Azure.CosmosRepository/Paging/PageQueryResult.cs
tests/Microsoft.Azure.CosmosRepositoryTests/InMemoryRepositoryTests.cs
tests/Microsoft.Azure.CosmosRepositoryTests/Microsoft.Azure.CosmosRepositoryTests.csproj

Currently any paging requests (in this package) also make a count request, this can be very expensive to run and therefore shouldn't be ran be default but should be opt in.
https://stackoverflow.com/questions/27745346/get-record-count-in-azure-documentdb
> For example from the above thread: 
16,400 records in single partition consumes 535 RUs.  
[Youngjae](https://stackoverflow.com/users/361100/youngjae)
[Jul 24, 2017 at 4:57](https://stackoverflow.com/questions/27745346/get-record-count-in-azure-documentdb#comment77508424_43560975)
- Added default variable to opt out (by default) or returning the count information from paging queries.
- This will require users who wish to get total count information to add an additional parameter to their calls.

Update paging methods to be opt in for returning count information

---

samples/BasicEventSourcingSample/Infrastructure/ShipRepository.cs
samples/BasicEventSourcingSample/Program.cs
samples/BasicEventSourcingSample/Projections/ShipInformationProjections.cs
src/Microsoft.Azure.CosmosEventSourcing/Builders/DefaultCosmosEventSourcingBuilder.cs
src/Microsoft.Azure.CosmosEventSourcing/Builders/ICosmosEventSourcingBuilder.cs
src/Microsoft.Azure.CosmosEventSourcing/DefaultEventStore.cs
src/Microsoft.Azure.CosmosEventSourcing/Extensions/EventSourceExtensions.cs
src/Microsoft.Azure.CosmosEventSourcing/Extensions/ExpressionExtensions.cs
src/Microsoft.Azure.CosmosEventSourcing/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Azure.CosmosEventSourcing/IEventStore.cs
src/Microsoft.Azure.CosmosEventSourcing/Projections/EventBasedEventSourceProjectionBuilder.cs
src/Microsoft.Azure.CosmosEventSourcing/Projections/IEventProjectionHandler.cs
tests/Microsoft.Azure.CosmosEventSourcingTests/EventStoreTests.cs

There may be common data stored on an `EventSource` that might not be on every `IPersistedEvent` which a user may want access to. This also allows access to the `Id` on the `EventSource` which could be used in an event inbox to stop duplicates being processed for example.
I felt this better describes this as just a store of events and not an `IRepository<T>` as I feel you should always have a single container per set of events you are storing.
This could be useful pulling reports etc being able to find all of a given event or all of a set of events.

Renaming, few extra methods, extra data available on projections.

---

src/Microsoft.Azure.CosmosRepository/Exceptions/BatchOperationException.cs
src/Microsoft.Azure.CosmosRepository/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Azure.CosmosRepository/Extensions/ValueTaskExtensions.cs
src/Microsoft.Azure.CosmosRepository/Repositories/DefaultRepository.Batch.cs
src/Microsoft.Azure.CosmosRepository/Repositories/IBatchRepository.cs
src/Microsoft.Azure.CosmosRepository/Repositories/IRepository.cs
src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.cs
tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/ChangeFeedBasicTests.cs
tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/TransactionalBatchTests.cs

Related to #151 
This is the first pass and allows items to be created, updated, and deleted as of a batch.
I have plans for a builder of a kind that will allow items that share the same partition key to having some more flexible operations, building up a transaction which I also think will be very nice. This is a good start tho and will have its use cases.
I see this working well and a kind of stepping stone for the issue described here #224

Added basic batch support

---

.github/workflows/build-validation.yml
.github/workflows/nuget-publish.yml

I have had to turn these off, for now, the tests require 3 containers, one for the events, one for the leases container for the change feed & one for the projections. This breaks the 1000 RU limit, I will look at setting up another account another time.

CosmosEventSourcing - Acceptance test turn off

---

src/Microsoft.Azure.CosmosEventSourcing/Aggregates/AggregateRoot.cs
src/Microsoft.Azure.CosmosEventSourcing/Events/AtomicEvent.cs
src/Microsoft.Azure.CosmosEventSourcing/Items/EventItem.cs
tests/Microsoft.Azure.CosmosEventSourcingTests/Aggregates/AggregateRootTests.cs
tests/Microsoft.Azure.CosmosEventSourcingTests/Items/EventItemTests.cs

We had an issue where the sequence number of events where being duplicated this was because of the Etags and optimistic concurrency not propagating properly between the `AggregateRoot` and the `EventItem` through the `AtomicEvent`'s.

Fix ETag Bug with Batch Updates

---

src/Microsoft.Azure.CosmosRepository/Options/RepositoryOptions.cs
src/Microsoft.Azure.CosmosRepository/Services/DefaultCosmosContainerService.cs

This defaults to the original behaviour of create if not exists. This is great for local dev and small projects.
Larger projects might use infrastructure as code to provision databases and containers. This means the create call is not needed. A small performance benefit can be gained from a read vs a create if not exists.
In addition if you were to use a managed identity to connect to cosmos DB. The create if not exists operation requires more permissions than just read so that can be another benefit.

Ability to opt out auto resource creation

---

docs/event-sourcing/src/projections/README.md
src/Microsoft.Azure.CosmosEventSourcing/Builders/DefaultCosmosEventSourcingBuilder.cs
src/Microsoft.Azure.CosmosEventSourcing/ChangeFeed/DefaultEventSourcingProcessor.cs
src/Microsoft.Azure.CosmosEventSourcing/Converters/DomainEventConverter.cs
src/Microsoft.Azure.CosmosEventSourcing/Events/NonDeserializableEvent.cs
src/Microsoft.Azure.CosmosEventSourcing/Projections/DefaultDomainEventProjection.cs

- Support for a more robust deserialization routine using a new `NonDeserializableEvent` to let a consumer detect errors better.
- Support for scoped handlers (ahead of some correlation ID planned work)
- Docs on the new `NonDeserializableEvent` and how it is used, and why it is important to handle

Better error handling on non-deserializable event types - favor scoped handlers

---

docs/event-sourcing/src/event-store/persistence/README.md
samples/Microsoft.Azure.CosmosEventSourcing/BasicEventSourcingSample/BasicEventSourcingSample.csproj
samples/Microsoft.Azure.CosmosEventSourcing/BasicEventSourcingSample/Program.cs
samples/Microsoft.Azure.CosmosEventSourcing/EventSourcingJobsTracker/Program.cs
src/Microsoft.Azure.CosmosEventSourcing/ChangeFeed/DefaultEventSourcingProcessor.cs
src/Microsoft.Azure.CosmosEventSourcing/Context/DefaultContextService.cs
src/Microsoft.Azure.CosmosEventSourcing/Context/IContextService.cs
src/Microsoft.Azure.CosmosEventSourcing/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Azure.CosmosEventSourcing/Items/EventItem.cs
src/Microsoft.Azure.CosmosEventSourcing/Projections/DefaultDomainEventProjection.cs
src/Microsoft.Azure.CosmosEventSourcing/Stores/DefaultEventStore.Def.cs
src/Microsoft.Azure.CosmosEventSourcing/Stores/DefaultEventStore.Write.cs
tests/Microsoft.Azure.CosmosEventSourcingTests/Stores/EventStoreTests.PersistAggregates.cs
tests/Microsoft.Azure.CosmosEventSourcingTests/Stores/EventStoreTests.cs

1. Supports correlations ID's been written to events and stored within a scoped service
2. Remove the duplicate scope been created in `IDomainEventProjection`'s (it's already created before this is called)

Support correlation IDs and fix double scope being created

---

src/Microsoft.Azure.CosmosRepository/Builders/PatchOperationBuilder.cs
src/Microsoft.Azure.CosmosRepository/Repositories/DefaultRepository.Update.cs
tests/Microsoft.Azure.CosmosRepositoryTests/Builders/PatchOperationBuilderTests.cs

This pr acknowledge the used serialization option of the cosmos client for the patch operation builder
- fixes #270

Acknowledge serialization options of CosmosClient for PatchOperationBuilder

---

src/Microsoft.Azure.CosmosEventSourcing/Items/EventItem.cs
src/Microsoft.Azure.CosmosRepository/FullItem.cs
tests/Microsoft.Azure.CosmosEventSourcingTests/Items/EventItemTests.cs
tests/Microsoft.Azure.CosmosRepositoryTests/Items/FullItemTests.cs
tests/Microsoft.Azure.CosmosRepositoryTests/Microsoft.Azure.CosmosRepositoryTests.csproj
tests/Microsoft.Azure.CosmosRepositoryTests/Stubs/TestItem.cs

Adds `NullValueHandling.Ignore` for the `TimeToLive` wrapper property on both `EventItem` and `FullItem`.
Addresses issue #314

ignore timeToLive when null

---

src/Microsoft.Azure.CosmosEventSourcing/Exceptions/EventItemPartitionKeyAttributeRequiredException.cs

This one took my co-worker @mkercheval-tva hours to figure out because the message led him to believe that he was required to have an attribute identifying the partition key even though we already had another Aggregate type working without using that attribute which was confounding to him.
Problem turned out to be that he was calling the overload of PersistAsync (in DefaultEventStore.Write) where you don't explicitly specify the partition key.
Just a minor improvement that may save someone time.

Improve exception messaging when there is no EventItemPartitionKey attribute explicitly defined

---

Directory.Packages.props
docs/cosmos-repo/content/6-miscellaneous/healthchecks/_index.md
samples/Microsoft.Azure.CosmosEventSourcing/BasicEventSourcingSample/BasicEventSourcingSample.csproj
samples/Microsoft.Azure.CosmosEventSourcing/BasicEventSourcingSample/Program.cs
src/Microsoft.Azure.CosmosRepository.AspNetCore/Extensions/HealthChecksBuilderExtensions.cs
src/Microsoft.Azure.CosmosRepository.AspNetCore/Microsoft.Azure.CosmosRepository.AspNetCore.csproj
src/Microsoft.Azure.CosmosRepository/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Azure.CosmosRepository/Providers/DefaultCosmosClientProvider.cs
src/Microsoft.Azure.CosmosRepository/Providers/DefaultCosmosItemConfigurationProvider.cs
src/Microsoft.Azure.CosmosRepository/Providers/ICosmosClientProvider.cs
src/Microsoft.Azure.CosmosRepository/Providers/ICosmosItemConfigurationProvider.cs
src/Microsoft.Azure.CosmosRepository/Visibility.cs
tests/Microsoft.Azure.CosmosRepositoryTests/Providers/DefaultCosmosItemConfigurationProviderTests.cs
tests/Microsoft.Azure.CosmosRepositoryTests/Stubs/TestCosmosClientProvider.cs

Adds functionality discussed in #366.
Closes #366 
Adds support for [AspNet Core Health Checks](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks) using the [HealthChecks.CosmosDb](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.CosmosDb/README.md) package.
To configure Cosmos DB health checks:  
```csharp
services.AddHealthChecks().AddCosmosRepository();
```
By default, this will scan all of the assemblies in your solution to locate the container names for each of your `IItem` types.  To refine this, and potentially reduce startup times, pass in the Assemblies containing your `IItem` types:
```csharp
services.AddHealthChecks().AddCosmosRepository(assemblies: typeof(ExampleItem).Assembly);
```
The Cosmos Repository …

[feat] Add health checks

---

.github/workflows/nuget-publish.yml

Fixes the Nuget release for the cosmos event sourcing project. This remains a pre-release package.

ci(nuget-release): fix cosmos event sourcing pre-release

---

src/Microsoft.Azure.CosmosRepository/ChangeFeed/ChangeFeedOptions.cs
src/Microsoft.Azure.CosmosRepository/ChangeFeed/DefaultConatinerChangeFeedProcessor.cs
tests/Microsoft.Azure.CosmosRepositoryTests/ChangeFeed/ChangeFeedOptionsTests.cs

Adds an option on `ChangeFeedOptions` used to set `ChangeFeedProcessorBuilder.WithStartTime`

add property to set 'WithStartTime' on change feed

---

src/Microsoft.Azure.CosmosRepository/Providers/DefaultCosmosClientProvider.cs
tests/Microsoft.Azure.CosmosRepositoryTests/Providers/DefaultCosmosClientProviderTests.cs

add missing await to async test asserts causing build failure.

add await to async test asserts

---

src/Microsoft.Azure.CosmosRepository/Options/RepositoryOptions.cs
src/Microsoft.Azure.CosmosRepository/Providers/ICosmosContainerProvider.cs

where each tenant connects to their own specific Cosmos DB
Along with the previous change I did to make ICosmosClientProvider public (https://github.com/IEvangelist/azure-cosmos-dotnet-repository/issues/398)
* ICosmosContainerProvider  - made this public, the default implementation caches containers, I needed a custom implementation to cache these per Tenant
* RepositoryOptions
- I made `DatabaseId`, `ContainerId` and `ConnectionString` virtual, again in my implementation I need these to be tenant specific, making these virtual allows me replace this with a multi-tenant version of RepositoryOptions

Follow up on Issue 398 : I'm attempting to use the library in a Multi Tenant scenario

---

src/Microsoft.Azure.CosmosRepository/Builders/PatchOperationBuilder.cs
src/Microsoft.Azure.CosmosRepository/Extensions/ExpressionExtensions.cs
src/Microsoft.Azure.CosmosRepository/Internals/InternalPatchOperation.cs
src/Microsoft.Azure.CosmosRepository/Repositories/InMemoryRepository.Update.cs
tests/Microsoft.Azure.CosmosRepositoryTests/InMemoryRepositoryTests.cs

I would like to propose a new solution to generate a path for Patch operations.
Currently, when a property is selected using a lambda to create a path for a Patch operation, the last property is selected and only the path is created based on that property. (Example: **x => x.NestedObject.Property1** creates for us path **/property1**).
The proposed solution creates a full path for the Patch operation taking into account all the properties that have been selected in the lambda. (Example: **x => x.NestedObject.Property1** creates for us path **/nestedObject/property1**)

Add full path support for the patch operations

---

src/Microsoft.Azure.CosmosRepository/Repositories/IReadOnlyRepository.cs

I would like to propose adding a parameter for page size to PageAsync which returns IAsyncEnumerable.
The default size will still remain 25 but if someone wanted to change it there would be an option to do so.
I think it would be possible to achieve the same result with #437 but it is not clear when it will be finished.

Add page size parameter to PageAsync with IAsyncEnumerable
